source 'https://rubygems.org'

gem 'rails', '4.1.0'
gem 'pg'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'activerecord', '~> 4.1.0'
gem 'rails_12factor', '~> 0.0.2'
gem 'faraday', '~> 0.9.0'
gem 'dotenv', '~> 0.11.1'
